INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (1, 'Retirer quatre cartes [[icon-plus-zero]]', 1, 6);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (2, 'Remplacer une carte [[icon-minus-one]] par une carte [[icon-plus-one]]', 3, 6);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (3, 'Ajouter une carte [[icon-minus-two]] et deux carte [[icon-plus-two]]', 1, 6);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (4, 'Ajouter une carte [[icon-plus-one]] IMMOBILISATION [[icon-immobilize]]', 2, 6);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (5, 'Ajouter une carte [[icon-plus-two]] CONFUSION [[icon-muddle]]', 2, 6);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (6, 'Ajouter deux cartes [[icon-redraw]] POUSSEE [[icon-push]] 2', 1, 6);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (7, 'Ajouter deux cartes [[icon-redraw]] [[icon-earth]]', 2, 6);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (8, 'Ajouter deux cartes [[icon-redraw]] [[icon-wind]]', 1, 6);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (9, 'Ignorer les effets négatifs des objets', 1, 6);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (10, 'Ignorer les effets négatifs des scénarios', 1, 6);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (11, 'Retirer deux cartes [[icon-minus-one]]', 2, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (12, 'Retirer quatre cartes [[icon-plus-zero]]', 1, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (13, 'Remplacer deux cartes [[icon-plus-one]] par deux cartes [[icon-plus-two]]', 1, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (14, 'Remplacer une carte [[icon-minus-two]] par une carte [[icon-plus-zero]]', 1, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (15, 'Ajouter une carte [[icon-plus-two]] [[icon-frost]]', 2, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (16, 'Ajouter deux cartes [[icon-redraw]] [[icon-plus-one]]', 2, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (17, 'Ajouter trois cartes [[icon-redraw]] TRACTION [[icon-pull]] 1', 1, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (18, 'Ajouter trois cartes [[icon-redraw]] CONFUSION [[icon-muddle]]', 1, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (19, 'Ajouter deux cartes [[icon-redraw]] IMMOBILISATION [[icon-immobilize]]', 1, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (20, 'Ajouter une carte [[icon-redraw]] ETOURDISSEMENT [[icon-stun]]', 1, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (21, 'Ajouter une carte [[icon-redraw]] DESARMEMENT [[icon-disarm]] et une carte [[icon-redraw]] CONFUSION [[icon-muddle]]', 1, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (22, 'Ignorer les effets négatifs des scénarios', 1, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (23, 'Retirer quatre carte [[icon-minus-zero]]', 1, 1);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (24, 'Remplacer une carte [[icon-minus-one]] par une carte [[icon-plus-one]]', 2, 1);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (25, 'Ajouter deux cartes [[icon-plus-one]]', 2, 1);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (26, 'Ajouter une carte [[icon-plus-zero]] ETOURDISSEMENT [[icon-stun]]', 1, 1);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (27, 'Ajouter une carte [[icon-minus-one]] BLESSRUE [[icon-wound]]', 1, 1);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (28, 'Ajouter une carte [[icon-plus-one]] IMMOBILISATION [[icon-immobilize]]', 1, 1);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (29, 'Ajouter une carte [[icon-plus-one]] MALEDICTION [[icon-curse]]', 1, 1);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (30, 'Ajouter une carte [[icon-plus-two]] [[icon-fire]]', 2, 1);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (31, 'Ajouter une carte [[icon-plus-two]] [[icon-frost]]', 2, 1);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (32, 'Ajouter une carte [[icon-redraw]] [[icon-earth]] et une carte [[icon-redraw]] [[icon-wind]]', 1, 1);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (33, 'Ajouter une carte [[icon-redraw]] [[icon-light]] et une carte [[icon-redraw]] [[icon-darkness]]', 1, 1);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (34, 'Retirer deux cartes [[icon-minus-one]]', 2, 3);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (35, 'Retirer quatre cartes [[icon-plus-zero]]', 1, 3);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (36, 'Remplacer une carte [[icon-minus-two]] par une carte [[icon-plus-zero]]', 1, 3);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (37, 'Remplacer une carte [[icon-minus-one]] par une carte [[icon-plus-one]]', 1, 3);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (38, 'Remplace une carte [[icon-plus-zero]] par une carte [[icon-plus-two]]', 2, 3);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (39, 'Ajouter deux cartes [[icon-redraw]] [[icon-plus-one]]', 2, 3);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (40, 'Ajouter deux cartes [[icon-redrax]] PERFORATION [[icon-perforation]] 3', 1, 3);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (41, 'Ajouter deux cartes [[icon-redraw]] EMPOISONEMENT [[icon-poison]]', 2, 3);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (42, 'Ajouter deux cartes [[icon-redraw]] CONFUSION [[icon-muddle]]', 1, 3);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (43, 'Ajouter une carte [[icon-redraw]] INVISIBILITE [[icon-invisibility]]', 1, 3);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (44, 'Ignorer les effets négatifs des scénarios', 1, 3);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (45, 'Retirer deux carte [[icon-minus-one]]', 2, 9);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (46, 'Retirer quatre cartes [[icon-plus-zero]]', 1, 9);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (47, 'Remplacer une carte [[icon-minus-two]] par une carte [[icon-plus-zero]]', 1, 9);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (48, 'Remplacer une carte [[icon-plus-zero]] par une carte [[icon-plus-two]]', 1, 9);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (49, 'Ajouter deux cartes [[icon-redraw]] [[icon-plus-one]]', 2, 9);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (50, 'Ajouter deux cartes [[icon-redraw]] [[icon-health]]', 2, 9);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (51, 'Ajouter une carte [[icon-redraw]] ETOURDISSEMENT [[icon-stun]]', 1, 9);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (52, 'Ajouter deux cartes [[icon-redraw]] [[icon-sun]]', 2, 9);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (53, 'Ajouter deux cartes [[icon-redraw]] Bouclier [[icon-shield]] 1, sur vous-même', 1, 9);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (54, 'Ignorer les effets des objets et ajouter deux cartes [[icon-plus-one]]', 1, 9);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (55, 'Ignorer les effets négatifs des scénarios', 1, 9);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (56, 'Retirer deux cartes [[icon-minus-one]]', 2, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (57, 'Remplacer une carte [[icon-minus-one]] par une carte [[icon-plus-one]]', 1, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (58, 'Remplacer une carte [[icon-plus-zero]] par une carte [[icon-plus-two]]', 2, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (59, 'Ajouter trois cartes [[icon-plus-zero]] [[icon-fire]]', 1, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (60, 'Ajouter trois cartes [[icon-plus-zero]] [[icon-frost]]', 1, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (61, 'Ajouter trois cartes [[icon-plus-zero]] [[icon-wind]]', 1, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (62, 'Ajouter trois cartes [[icon-plus-zero]] [[icon-earth]]', 1, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (63, 'Remplacer deux cartes [[icon-plus-zero]] par une carte [[icon-plus-zero]] [[icon-fire]] et une carte [[icon-plus-zero]] [[icon-earth]]', 1, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (64, 'Remplacer deux cartes [[icon-plus-zero]] par une carte [[icon-plus-zero]] [[icon-frost]] et une carte [[icon-plus-zero]] [[icon-wind]]', 1, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (65, 'Ajouter deux cartes [[icon-plus-one]] POUSSEE [[icon-push]] 1', 1, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (66, 'Ajouter une carte [[icon-plus-one]] BLESSURE [[icon-wound]]', 1, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (67, 'Ajouter une carte [[icon-plus-zero]] ETOURDISSEMENT [[icon-stun]]', 1, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (68, 'Ajouter une carte [[icon-plus-zero]] AJOUTER UNE CIBLE [[icon-target]]', 1, 7);