UPDATE gloom_api.perks SET content = 'Retirer quatre cartes [[icon-plus-zero]]', quantity = 1, game_character_id = 6 WHERE id = 1;
UPDATE gloom_api.perks SET content = 'Remplacer une carte [[icon-minus-one]] par une carte [[icon-plus-one]]', quantity = 3, game_character_id = 6 WHERE id = 2;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-minus-two]] et deux carte [[icon-plus-two]]', quantity = 1, game_character_id = 6 WHERE id = 3;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-one]] IMMOBILISATION [[icon-immobilize]]', quantity = 2, game_character_id = 6 WHERE id = 4;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-two]] CONFUSION [[icon-muddle]]', quantity = 2, game_character_id = 6 WHERE id = 5;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] POUSSEE [[icon-push]] 2', quantity = 1, game_character_id = 6 WHERE id = 6;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] [[icon-earth]]', quantity = 2, game_character_id = 6 WHERE id = 7;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] [[icon-wind]]', quantity = 1, game_character_id = 6 WHERE id = 8;
UPDATE gloom_api.perks SET content = 'Ignorer les effets négatifs des objets', quantity = 1, game_character_id = 6 WHERE id = 9;
UPDATE gloom_api.perks SET content = 'Ignorer les effets négatifs des scénarios', quantity = 1, game_character_id = 6 WHERE id = 10;
UPDATE gloom_api.perks SET content = 'Retirer deux cartes [[icon-minus-one]]', quantity = 2, game_character_id = 5 WHERE id = 11;
UPDATE gloom_api.perks SET content = 'Retirer quatre cartes [[icon-plus-zero]]', quantity = 1, game_character_id = 5 WHERE id = 12;
UPDATE gloom_api.perks SET content = 'Remplacer deux cartes [[icon-plus-one]] par deux cartes [[icon-plus-two]]', quantity = 2, game_character_id = 5 WHERE id = 13;
UPDATE gloom_api.perks SET content = 'Remplacer une carte [[icon-minus-two]] par une carte [[icon-plus-zero]]', quantity = 1, game_character_id = 5 WHERE id = 14;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-two]] [[icon-frost]]', quantity = 2, game_character_id = 5 WHERE id = 15;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] [[icon-plus-one]]', quantity = 2, game_character_id = 5 WHERE id = 16;
UPDATE gloom_api.perks SET content = 'Ajouter trois cartes [[icon-redraw]] TRACTION [[icon-pull]] 1', quantity = 1, game_character_id = 5 WHERE id = 17;
UPDATE gloom_api.perks SET content = 'Ajouter trois cartes [[icon-redraw]] CONFUSION [[icon-muddle]]', quantity = 1, game_character_id = 5 WHERE id = 18;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] IMMOBILISATION [[icon-immobilize]]', quantity = 1, game_character_id = 5 WHERE id = 19;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-redraw]] ETOURDISSEMENT [[icon-stun]]', quantity = 1, game_character_id = 5 WHERE id = 20;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-redraw]] DESARMEMENT [[icon-disarm]] et une carte [[icon-redraw]] CONFUSION [[icon-muddle]]', quantity = 1, game_character_id = 5 WHERE id = 21;
UPDATE gloom_api.perks SET content = 'Ignorer les effets négatifs des scénarios', quantity = 1, game_character_id = 5 WHERE id = 22;
UPDATE gloom_api.perks SET content = 'Retirer quatre carte [[icon-minus-zero]]', quantity = 1, game_character_id = 1 WHERE id = 23;
UPDATE gloom_api.perks SET content = 'Remplacer une carte [[icon-minus-one]] par une carte [[icon-plus-one]]', quantity = 2, game_character_id = 1 WHERE id = 24;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-plus-one]]', quantity = 2, game_character_id = 1 WHERE id = 25;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-zero]] ETOURDISSEMENT [[icon-stun]]', quantity = 1, game_character_id = 1 WHERE id = 26;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-minus-one]] BLESSRUE [[icon-wound]]', quantity = 1, game_character_id = 1 WHERE id = 27;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-one]] IMMOBILISATION [[icon-immobilize]]', quantity = 1, game_character_id = 1 WHERE id = 28;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-one]] MALEDICTION [[icon-curse]]', quantity = 1, game_character_id = 1 WHERE id = 29;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-two]] [[icon-fire]]', quantity = 2, game_character_id = 1 WHERE id = 30;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-two]] [[icon-frost]]', quantity = 2, game_character_id = 1 WHERE id = 31;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-redraw]] [[icon-earth]] et une carte [[icon-redraw]] [[icon-wind]]', quantity = 1, game_character_id = 1 WHERE id = 32;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-redraw]] [[icon-light]] et une carte [[icon-redraw]] [[icon-darkness]]', quantity = 1, game_character_id = 1 WHERE id = 33;
UPDATE gloom_api.perks SET content = 'Retirer deux cartes [[icon-minus-one]]', quantity = 2, game_character_id = 3 WHERE id = 34;
UPDATE gloom_api.perks SET content = 'Retirer quatre cartes [[icon-plus-zero]]', quantity = 1, game_character_id = 3 WHERE id = 35;
UPDATE gloom_api.perks SET content = 'Remplacer une carte [[icon-minus-two]] par une carte [[icon-plus-zero]]', quantity = 1, game_character_id = 3 WHERE id = 36;
UPDATE gloom_api.perks SET content = 'Remplacer une carte [[icon-minus-one]] par une carte [[icon-plus-one]]', quantity = 1, game_character_id = 3 WHERE id = 37;
UPDATE gloom_api.perks SET content = 'Remplace une carte [[icon-plus-zero]] par une carte [[icon-plus-two]]', quantity = 2, game_character_id = 3 WHERE id = 38;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] [[icon-plus-one]]', quantity = 2, game_character_id = 3 WHERE id = 39;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redrax]] PERFORATION [[icon-perforation]] 3', quantity = 1, game_character_id = 3 WHERE id = 40;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] EMPOISONEMENT [[icon-poison]]', quantity = 2, game_character_id = 3 WHERE id = 41;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] CONFUSION [[icon-muddle]]', quantity = 1, game_character_id = 3 WHERE id = 42;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-redraw]] INVISIBILITE [[icon-invisibility]]', quantity = 1, game_character_id = 3 WHERE id = 43;
UPDATE gloom_api.perks SET content = 'Ignorer les effets négatifs des scénarios', quantity = 1, game_character_id = 3 WHERE id = 44;