UPDATE gloom_api.perks SET content = 'Retirer quatre cartes [[icon-plus-zero]]', quantity = 1, game_character_id = 6 WHERE id = 1;
UPDATE gloom_api.perks SET content = 'Remplacer une carte [[icon-minus-one]] par une carte [[icon-plus-one]]', quantity = 3, game_character_id = 6 WHERE id = 2;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-minus-two]] et deux carte [[icon-plus-two]]', quantity = 1, game_character_id = 6 WHERE id = 3;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-one]] IMMOBILISATION [[icon-immobilize]]', quantity = 2, game_character_id = 6 WHERE id = 4;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-two]] CONFUSION [[icon-muddle]]', quantity = 2, game_character_id = 6 WHERE id = 5;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] POUSSEE [[icon-push]] 2', quantity = 1, game_character_id = 6 WHERE id = 6;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] [[icon-earth]]', quantity = 2, game_character_id = 6 WHERE id = 7;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] [[icon-wind]]', quantity = 1, game_character_id = 6 WHERE id = 8;
UPDATE gloom_api.perks SET content = 'Ignorer les effets négatifs des objets', quantity = 1, game_character_id = 6 WHERE id = 9;
UPDATE gloom_api.perks SET content = 'Ignorer les effets négatifs des scénarios', quantity = 1, game_character_id = 6 WHERE id = 10;
UPDATE gloom_api.perks SET content = 'Retirer deux cartes [[icon-minus-one]]', quantity = 2, game_character_id = 5 WHERE id = 11;
UPDATE gloom_api.perks SET content = 'Retirer quatre cartes [[icon-plus-zero]]', quantity = 1, game_character_id = 5 WHERE id = 12;
UPDATE gloom_api.perks SET content = 'Remplacer deux cartes [[icon-plus-one]] par deux cartes [[icon-plus-two]]', quantity = 1, game_character_id = 5 WHERE id = 13;
UPDATE gloom_api.perks SET content = 'Remplacer une carte [[icon-minus-two]] par une carte [[icon-plus-zero]]', quantity = 1, game_character_id = 5 WHERE id = 14;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-two]] [[icon-ice]]', quantity = 2, game_character_id = 5 WHERE id = 15;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] [[icon-plus-one]]', quantity = 2, game_character_id = 5 WHERE id = 16;
UPDATE gloom_api.perks SET content = 'Ajouter trois cartes [[icon-redraw]] TRACTION [[icon-pull]] 1', quantity = 1, game_character_id = 5 WHERE id = 17;
UPDATE gloom_api.perks SET content = 'Ajouter trois cartes [[icon-redraw]] CONFUSION [[icon-muddle]]', quantity = 1, game_character_id = 5 WHERE id = 18;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] IMMOBILISATION [[icon-immobilize]]', quantity = 1, game_character_id = 5 WHERE id = 19;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-redraw]] ETOURDISSEMENT [[icon-stun]]', quantity = 1, game_character_id = 5 WHERE id = 20;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-redraw]] DESARMEMENT [[icon-disarm]] et une carte [[icon-redraw]] CONFUSION [[icon-muddle]]', quantity = 1, game_character_id = 5 WHERE id = 21;
UPDATE gloom_api.perks SET content = 'Ignorer les effets négatifs des scénarios', quantity = 1, game_character_id = 5 WHERE id = 22;
UPDATE gloom_api.perks SET content = 'Retirer quatre carte [[icon-minus-zero]]', quantity = 1, game_character_id = 1 WHERE id = 23;
UPDATE gloom_api.perks SET content = 'Remplacer une carte [[icon-minus-one]] par une carte [[icon-plus-one]]', quantity = 2, game_character_id = 1 WHERE id = 24;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-plus-one]]', quantity = 2, game_character_id = 1 WHERE id = 25;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-zero]] ETOURDISSEMENT [[icon-stun]]', quantity = 1, game_character_id = 1 WHERE id = 26;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-one]] BLESSURE [[icon-wound]]', quantity = 1, game_character_id = 1 WHERE id = 27;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-one]] IMMOBILISATION [[icon-immobilize]]', quantity = 1, game_character_id = 1 WHERE id = 28;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-one]] MALEDICTION [[icon-curse]]', quantity = 1, game_character_id = 1 WHERE id = 29;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-two]] [[icon-fire]]', quantity = 2, game_character_id = 1 WHERE id = 30;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-two]] [[icon-ice]]', quantity = 2, game_character_id = 1 WHERE id = 31;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-redraw]] [[icon-earth]] et une carte [[icon-redraw]] [[icon-wind]]', quantity = 1, game_character_id = 1 WHERE id = 32;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-redraw]] [[icon-sun]] et une carte [[icon-redraw]] [[icon-night]]', quantity = 1, game_character_id = 1 WHERE id = 33;
UPDATE gloom_api.perks SET content = 'Retirer deux cartes [[icon-minus-one]]', quantity = 2, game_character_id = 3 WHERE id = 34;
UPDATE gloom_api.perks SET content = 'Retirer quatre cartes [[icon-plus-zero]]', quantity = 1, game_character_id = 3 WHERE id = 35;
UPDATE gloom_api.perks SET content = 'Remplacer une carte [[icon-minus-two]] par une carte [[icon-plus-zero]]', quantity = 1, game_character_id = 3 WHERE id = 36;
UPDATE gloom_api.perks SET content = 'Remplacer une carte [[icon-minus-one]] par une carte [[icon-plus-one]]', quantity = 1, game_character_id = 3 WHERE id = 37;
UPDATE gloom_api.perks SET content = 'Remplace une carte [[icon-plus-zero]] par une carte [[icon-plus-two]]', quantity = 2, game_character_id = 3 WHERE id = 38;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] [[icon-plus-one]]', quantity = 2, game_character_id = 3 WHERE id = 39;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] PERFORATION [[icon-pierce]] 3', quantity = 1, game_character_id = 3 WHERE id = 40;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] EMPOISONEMENT [[icon-poison]]', quantity = 2, game_character_id = 3 WHERE id = 41;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] CONFUSION [[icon-muddle]]', quantity = 1, game_character_id = 3 WHERE id = 42;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-redraw]] INVISIBILITE [[icon-invisibility]]', quantity = 1, game_character_id = 3 WHERE id = 43;
UPDATE gloom_api.perks SET content = 'Ignorer les effets négatifs des scénarios', quantity = 1, game_character_id = 3 WHERE id = 44;
UPDATE gloom_api.perks SET content = 'Retirer deux carte [[icon-minus-one]]', quantity = 2, game_character_id = 9 WHERE id = 45;
UPDATE gloom_api.perks SET content = 'Retirer quatre cartes [[icon-plus-zero]]', quantity = 1, game_character_id = 9 WHERE id = 46;
UPDATE gloom_api.perks SET content = 'Remplacer une carte [[icon-minus-two]] par une carte [[icon-plus-zero]]', quantity = 1, game_character_id = 9 WHERE id = 47;
UPDATE gloom_api.perks SET content = 'Remplacer une carte [[icon-plus-zero]] par une carte [[icon-plus-two]]', quantity = 1, game_character_id = 9 WHERE id = 48;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] [[icon-plus-one]]', quantity = 2, game_character_id = 9 WHERE id = 49;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] [[icon-health]]', quantity = 2, game_character_id = 9 WHERE id = 50;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-redraw]] ETOURDISSEMENT [[icon-stun]]', quantity = 1, game_character_id = 9 WHERE id = 51;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] [[icon-sun]]', quantity = 2, game_character_id = 9 WHERE id = 52;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] Bouclier [[icon-shield]] 1, sur vous-même', quantity = 1, game_character_id = 9 WHERE id = 53;
UPDATE gloom_api.perks SET content = 'Ignorer les effets des objets et ajouter deux cartes [[icon-plus-one]]', quantity = 1, game_character_id = 9 WHERE id = 54;
UPDATE gloom_api.perks SET content = 'Ignorer les effets négatifs des scénarios', quantity = 1, game_character_id = 9 WHERE id = 55;
UPDATE gloom_api.perks SET content = 'Retirer deux cartes [[icon-minus-one]]', quantity = 2, game_character_id = 7 WHERE id = 56;
UPDATE gloom_api.perks SET content = 'Remplacer une carte [[icon-minus-one]] par une carte [[icon-plus-one]]', quantity = 1, game_character_id = 7 WHERE id = 57;
UPDATE gloom_api.perks SET content = 'Remplacer une carte [[icon-plus-zero]] par une carte [[icon-plus-two]]', quantity = 2, game_character_id = 7 WHERE id = 58;
UPDATE gloom_api.perks SET content = 'Ajouter trois cartes [[icon-plus-zero]] [[icon-fire]]', quantity = 1, game_character_id = 7 WHERE id = 59;
UPDATE gloom_api.perks SET content = 'Ajouter trois cartes [[icon-plus-zero]] [[icon-ice]]', quantity = 1, game_character_id = 7 WHERE id = 60;
UPDATE gloom_api.perks SET content = 'Ajouter trois cartes [[icon-plus-zero]] [[icon-wind]]', quantity = 1, game_character_id = 7 WHERE id = 61;
UPDATE gloom_api.perks SET content = 'Ajouter trois cartes [[icon-plus-zero]] [[icon-earth]]', quantity = 1, game_character_id = 7 WHERE id = 62;
UPDATE gloom_api.perks SET content = 'Remplacer deux cartes [[icon-plus-zero]] par une carte [[icon-plus-zero]] [[icon-fire]] et une carte [[icon-plus-zero]] [[icon-earth]]', quantity = 1, game_character_id = 7 WHERE id = 63;
UPDATE gloom_api.perks SET content = 'Remplacer deux cartes [[icon-plus-zero]] par une carte [[icon-plus-zero]] [[icon-ice]] et une carte [[icon-plus-zero]] [[icon-wind]]', quantity = 1, game_character_id = 7 WHERE id = 64;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-plus-one]] POUSSEE [[icon-push]] 1', quantity = 1, game_character_id = 7 WHERE id = 65;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-one]] BLESSURE [[icon-wound]]', quantity = 1, game_character_id = 7 WHERE id = 66;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-zero]] ETOURDISSEMENT [[icon-stun]]', quantity = 1, game_character_id = 7 WHERE id = 67;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-zero]] AJOUTER UNE CIBLE [[icon-target]]', quantity = 1, game_character_id = 7 WHERE id = 68;
UPDATE gloom_api.perks SET content = 'Retire deux cartes [[icon-minus-one]]', quantity = 1, game_character_id = 10 WHERE id = 69;
UPDATE gloom_api.perks SET content = 'Remplacer une carte [[icon-minus-two]] par une carte [[icon-plus-zero]]', quantity = 1, game_character_id = 10 WHERE id = 70;
UPDATE gloom_api.perks SET content = 'Remplacer une carte [[icon-minus-one]] par une carte [[icon-plus-one]]', quantity = 3, game_character_id = 10 WHERE id = 71;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-two]]', quantity = 2, game_character_id = 10 WHERE id = 72;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] BLESSURE [[icon-wound]]', quantity = 1, game_character_id = 10 WHERE id = 73;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] EMPOISONNEMENT [[icon-poison]]', quantity = 1, game_character_id = 10 WHERE id = 74;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] Soin [[icon-health]] 1', quantity = 3, game_character_id = 10 WHERE id = 75;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-redraw]] [[icon-fire]] et une carte [[icon-redraw]] [[icon-wind]]', quantity = 1, game_character_id = 10 WHERE id = 76;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-redraw]] [[icon-night]] et une carte [[icon-redraw]] [[icon-earth]]', quantity = 1, game_character_id = 10 WHERE id = 77;
UPDATE gloom_api.perks SET content = 'Ignorer les effets négatifs des scénarios et ajouter deux cartes [[icon-plus-one]]', quantity = 1, game_character_id = 10 WHERE id = 78;
UPDATE gloom_api.perks SET content = 'Retirer deux cartes [[icon-minus-1]]', quantity = 2, game_character_id = 8 WHERE id = 79;
UPDATE gloom_api.perks SET content = 'Retirer quatre catres [[icon-plus-zero]]', quantity = 1, game_character_id = 8 WHERE id = 80;
UPDATE gloom_api.perks SET content = 'Remplacer une carte [[icon-plus-zero]] par une carte [[icon-plus-two]]', quantity = 2, game_character_id = 8 WHERE id = 81;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] [[icon-plus-one]]', quantity = 2, game_character_id = 8 WHERE id = 82;
UPDATE gloom_api.perks SET content = 'Ajouter trois cartes [[icon-redraw]] CONFUSION [[icon-muddle]]', quantity = 1, game_character_id = 8 WHERE id = 83;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] PERFORATION [[icon-pierce]] 3', quantity = 1, game_character_id = 8 WHERE id = 84;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-redraw]] ETOURDISSEMENT [[icon-stun]]', quantity = 1, game_character_id = 8 WHERE id = 85;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-redraw]] AJOUTER UNE CIBLE [[icon-target]]', quantity = 1, game_character_id = 8 WHERE id = 86;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-zero]] Rafraîchir une carte objet', quantity = 3, game_character_id = 8 WHERE id = 87;
UPDATE gloom_api.perks SET content = 'Ignorer les effets négatifs des objets et ajouter deux cartes [[icon-plus-one]]', quantity = 1, game_character_id = 8 WHERE id = 88;
UPDATE gloom_api.perks SET content = 'Retirer deux cartes [[icon-minus-one]]', quantity = 1, game_character_id = 2 WHERE id = 89;
UPDATE gloom_api.perks SET content = 'Remplacer une carte [[icon-minus-one]] par une carte [[icon-plus-one]]', quantity = 1, game_character_id = 2 WHERE id = 90;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-plus-one]]', quantity = 2, game_character_id = 2 WHERE id = 91;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-three]]', quantity = 1, game_character_id = 2 WHERE id = 92;
UPDATE gloom_api.perks SET content = 'Ajouter trois cartes [[icon-redraw]] POUSSÉE [[icon-push]] 1', quantity = 2, game_character_id = 2 WHERE id = 93;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] PERFORATION [[icon-pierce]] 3', quantity = 1, game_character_id = 2 WHERE id = 94;
UPDATE gloom_api.perks SET content = 'Ajouter deux cartes [[icon-redraw]] ÉTOURDISSEMENT [[icon-stun]]', quantity = 2, game_character_id = 2 WHERE id = 95;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-redraw]] DÉSARMEMENT [[icon-disarm]] et une carte [[icon-redraw]] CONFUSION [[icon-muddle]]', quantity = 1, game_character_id = 2 WHERE id = 96;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-redraw]] AJOUTER UNE CIBLE [[icon-target]]', quantity = 2, game_character_id = 2 WHERE id = 97;
UPDATE gloom_api.perks SET content = 'Ajouter une carte [[icon-plus-one]] Bouclier [[icon-shield]] 1, sur vous-même', quantity = 1, game_character_id = 2 WHERE id = 98;
UPDATE gloom_api.perks SET content = 'Ignorer les effets négatifs des objets et ajouter une carte [[icon-plus-one]]', quantity = 1, game_character_id = 2 WHERE id = 99;