INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (1, 'Retirer quatre cartes [[icon-plus-zero]]', 1, 6);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (2, 'Remplacer une carte [[icon-minus-one]] par une carte [[icon-plus-one]]', 3, 6);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (3, 'Ajouter une carte [[icon-minus-two]] et deux carte [[icon-plus-two]]', 1, 6);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (4, 'Ajouter une carte [[icon-plus-one]] IMMOBILISATION [[icon-immobilize]]', 2, 6);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (5, 'Ajouter une carte [[icon-plus-two]] CONFUSION [[icon-muddle]]', 2, 6);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (6, 'Ajouter deux cartes [[icon-redraw]] POUSSEE [[icon-push]] 2', 1, 6);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (7, 'Ajouter deux cartes [[icon-redraw]] [[icon-earth]]', 2, 6);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (8, 'Ajouter deux cartes [[icon-redraw]] [[icon-wind]]', 1, 6);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (9, 'Ignorer les effets négatifs des objets', 1, 6);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (10, 'Ignorer les effets négatifs des scénarios', 1, 6);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (11, 'Retirer deux cartes [[icon-minus-one]]', 2, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (12, 'Retirer quatre cartes [[icon-plus-zero]]', 1, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (13, 'Remplacer deux cartes [[icon-plus-one]] par deux cartes [[icon-plus-two]]', 1, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (14, 'Remplacer une carte [[icon-minus-two]] par une carte [[icon-plus-zero]]', 1, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (15, 'Ajouter une carte [[icon-plus-two]] [[icon-ice]]', 2, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (16, 'Ajouter deux cartes [[icon-redraw]] [[icon-plus-one]]', 2, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (17, 'Ajouter trois cartes [[icon-redraw]] TRACTION [[icon-pull]] 1', 1, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (18, 'Ajouter trois cartes [[icon-redraw]] CONFUSION [[icon-muddle]]', 1, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (19, 'Ajouter deux cartes [[icon-redraw]] IMMOBILISATION [[icon-immobilize]]', 1, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (20, 'Ajouter une carte [[icon-redraw]] ETOURDISSEMENT [[icon-stun]]', 1, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (21, 'Ajouter une carte [[icon-redraw]] DESARMEMENT [[icon-disarm]] et une carte [[icon-redraw]] CONFUSION [[icon-muddle]]', 1, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (22, 'Ignorer les effets négatifs des scénarios', 1, 5);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (23, 'Retirer quatre carte [[icon-minus-zero]]', 1, 1);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (24, 'Remplacer une carte [[icon-minus-one]] par une carte [[icon-plus-one]]', 2, 1);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (25, 'Ajouter deux cartes [[icon-plus-one]]', 2, 1);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (26, 'Ajouter une carte [[icon-plus-zero]] ETOURDISSEMENT [[icon-stun]]', 1, 1);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (27, 'Ajouter une carte [[icon-plus-one]] BLESSURE [[icon-wound]]', 1, 1);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (28, 'Ajouter une carte [[icon-plus-one]] IMMOBILISATION [[icon-immobilize]]', 1, 1);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (29, 'Ajouter une carte [[icon-plus-one]] MALEDICTION [[icon-curse]]', 1, 1);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (30, 'Ajouter une carte [[icon-plus-two]] [[icon-fire]]', 2, 1);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (31, 'Ajouter une carte [[icon-plus-two]] [[icon-ice]]', 2, 1);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (32, 'Ajouter une carte [[icon-redraw]] [[icon-earth]] et une carte [[icon-redraw]] [[icon-wind]]', 1, 1);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (33, 'Ajouter une carte [[icon-redraw]] [[icon-sun]] et une carte [[icon-redraw]] [[icon-night]]', 1, 1);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (34, 'Retirer deux cartes [[icon-minus-one]]', 2, 3);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (35, 'Retirer quatre cartes [[icon-plus-zero]]', 1, 3);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (36, 'Remplacer une carte [[icon-minus-two]] par une carte [[icon-plus-zero]]', 1, 3);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (37, 'Remplacer une carte [[icon-minus-one]] par une carte [[icon-plus-one]]', 1, 3);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (38, 'Remplace une carte [[icon-plus-zero]] par une carte [[icon-plus-two]]', 2, 3);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (39, 'Ajouter deux cartes [[icon-redraw]] [[icon-plus-one]]', 2, 3);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (40, 'Ajouter deux cartes [[icon-redraw]] PERFORATION [[icon-pierce]] 3', 1, 3);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (41, 'Ajouter deux cartes [[icon-redraw]] EMPOISONEMENT [[icon-poison]]', 2, 3);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (42, 'Ajouter deux cartes [[icon-redraw]] CONFUSION [[icon-muddle]]', 1, 3);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (43, 'Ajouter une carte [[icon-redraw]] INVISIBILITE [[icon-invisibility]]', 1, 3);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (44, 'Ignorer les effets négatifs des scénarios', 1, 3);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (45, 'Retirer deux carte [[icon-minus-one]]', 2, 9);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (46, 'Retirer quatre cartes [[icon-plus-zero]]', 1, 9);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (47, 'Remplacer une carte [[icon-minus-two]] par une carte [[icon-plus-zero]]', 1, 9);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (48, 'Remplacer une carte [[icon-plus-zero]] par une carte [[icon-plus-two]]', 1, 9);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (49, 'Ajouter deux cartes [[icon-redraw]] [[icon-plus-one]]', 2, 9);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (50, 'Ajouter deux cartes [[icon-redraw]] [[icon-health]]', 2, 9);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (51, 'Ajouter une carte [[icon-redraw]] ETOURDISSEMENT [[icon-stun]]', 1, 9);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (52, 'Ajouter deux cartes [[icon-redraw]] [[icon-sun]]', 2, 9);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (53, 'Ajouter deux cartes [[icon-redraw]] Bouclier [[icon-shield]] 1, sur vous-même', 1, 9);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (54, 'Ignorer les effets des objets et ajouter deux cartes [[icon-plus-one]]', 1, 9);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (55, 'Ignorer les effets négatifs des scénarios', 1, 9);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (56, 'Retirer deux cartes [[icon-minus-one]]', 2, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (57, 'Remplacer une carte [[icon-minus-one]] par une carte [[icon-plus-one]]', 1, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (58, 'Remplacer une carte [[icon-plus-zero]] par une carte [[icon-plus-two]]', 2, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (59, 'Ajouter trois cartes [[icon-plus-zero]] [[icon-fire]]', 1, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (60, 'Ajouter trois cartes [[icon-plus-zero]] [[icon-ice]]', 1, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (61, 'Ajouter trois cartes [[icon-plus-zero]] [[icon-wind]]', 1, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (62, 'Ajouter trois cartes [[icon-plus-zero]] [[icon-earth]]', 1, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (63, 'Remplacer deux cartes [[icon-plus-zero]] par une carte [[icon-plus-zero]] [[icon-fire]] et une carte [[icon-plus-zero]] [[icon-earth]]', 1, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (64, 'Remplacer deux cartes [[icon-plus-zero]] par une carte [[icon-plus-zero]] [[icon-ice]] et une carte [[icon-plus-zero]] [[icon-wind]]', 1, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (65, 'Ajouter deux cartes [[icon-plus-one]] POUSSEE [[icon-push]] 1', 1, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (66, 'Ajouter une carte [[icon-plus-one]] BLESSURE [[icon-wound]]', 1, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (67, 'Ajouter une carte [[icon-plus-zero]] ETOURDISSEMENT [[icon-stun]]', 1, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (68, 'Ajouter une carte [[icon-plus-zero]] AJOUTER UNE CIBLE [[icon-target]]', 1, 7);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (69, 'Retire deux cartes [[icon-minus-one]]', 1, 10);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (70, 'Remplacer une carte [[icon-minus-two]] par une carte [[icon-plus-zero]]', 1, 10);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (71, 'Remplacer une carte [[icon-minus-one]] par une carte [[icon-plus-one]]', 3, 10);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (72, 'Ajouter une carte [[icon-plus-two]]', 2, 10);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (73, 'Ajouter deux cartes [[icon-redraw]] BLESSURE [[icon-wound]]', 1, 10);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (74, 'Ajouter deux cartes [[icon-redraw]] EMPOISONNEMENT [[icon-poison]]', 1, 10);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (75, 'Ajouter deux cartes [[icon-redraw]] Soin [[icon-health]] 1', 3, 10);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (76, 'Ajouter une carte [[icon-redraw]] [[icon-fire]] et une carte [[icon-redraw]] [[icon-wind]]', 1, 10);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (77, 'Ajouter une carte [[icon-redraw]] [[icon-night]] et une carte [[icon-redraw]] [[icon-earth]]', 1, 10);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (78, 'Ignorer les effets négatifs des scénarios et ajouter deux cartes [[icon-plus-one]]', 1, 10);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (79, 'Retirer deux cartes [[icon-minus-1]]', 2, 8);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (80, 'Retirer quatre catres [[icon-plus-zero]]', 1, 8);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (81, 'Remplacer une carte [[icon-plus-zero]] par une carte [[icon-plus-two]]', 2, 8);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (82, 'Ajouter deux cartes [[icon-redraw]] [[icon-plus-one]]', 2, 8);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (83, 'Ajouter trois cartes [[icon-redraw]] CONFUSION [[icon-muddle]]', 1, 8);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (84, 'Ajouter deux cartes [[icon-redraw]] PERFORATION [[icon-pierce]] 3', 1, 8);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (85, 'Ajouter une carte [[icon-redraw]] ETOURDISSEMENT [[icon-stun]]', 1, 8);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (86, 'Ajouter une carte [[icon-redraw]] AJOUTER UNE CIBLE [[icon-target]]', 1, 8);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (87, 'Ajouter une carte [[icon-plus-zero]] Rafraîchir une carte objet', 3, 8);
INSERT INTO gloom_api.perks (id, content, quantity, game_character_id) VALUES (88, 'Ignorer les effets négatifs des objets et ajouter deux cartes [[icon-plus-one]]', 1, 8);
INSERT INTO gloom.perks (id, content, quantity, game_character_id) VALUES (89, 'Retirer deux cartes [[icon-minus-one]]', 1, 2);
INSERT INTO gloom.perks (id, content, quantity, game_character_id) VALUES (90, 'Remplacer une carte [[icon-minus-one]] par une carte [[icon-plus-one]]', 1, 2);
INSERT INTO gloom.perks (id, content, quantity, game_character_id) VALUES (91, 'Ajouter deux cartes [[icon-plus-one]]', 2, 2);
INSERT INTO gloom.perks (id, content, quantity, game_character_id) VALUES (92, 'Ajouter une carte [[icon-plus-three]]', 1, 2);
INSERT INTO gloom.perks (id, content, quantity, game_character_id) VALUES (93, 'Ajouter trois cartes [[icon-redraw]] POUSSÉE [[icon-push]] 1', 2, 2);
INSERT INTO gloom.perks (id, content, quantity, game_character_id) VALUES (94, 'Ajouter deux cartes [[icon-redraw]] PERFORATION [[icon-pierce]] 3', 1, 2);
INSERT INTO gloom.perks (id, content, quantity, game_character_id) VALUES (95, 'Ajouter deux cartes [[icon-redraw]] ÉTOURDISSEMENT [[icon-stun]]', 2, 2);
INSERT INTO gloom.perks (id, content, quantity, game_character_id) VALUES (96, 'Ajouter une carte [[icon-redraw]] DÉSARMEMENT [[icon-disarm]] et une carte [[icon-redraw]] CONFUSION [[icon-muddle]]', 1, 2);
INSERT INTO gloom.perks (id, content, quantity, game_character_id) VALUES (97, 'Ajouter une carte [[icon-redraw]] AJOUTER UNE CIBLE [[icon-target]]', 2, 2);
INSERT INTO gloom.perks (id, content, quantity, game_character_id) VALUES (98, 'Ajouter une carte [[icon-plus-one]] Bouclier [[icon-shield]] 1, sur vous-même', 1, 2);
INSERT INTO gloom.perks (id, content, quantity, game_character_id) VALUES (99, 'Ignorer les effets négatifs des objets et ajouter une carte [[icon-plus-one]]', 1, 2);